lgvd_config:
  num_steps: 100
  lr: 1e-4
  tau: 0.01
  lr_min_ratio: 0.01

GDAPS_config:
  scale: 5.0

operator:
  name: inpainting
  mask_type: random  # box
  # mask_len_range: [128, 129]  # for box
  mask_prob_range: [ 0.70, 0.71 ]  # for random
  resolution: 256
  sigma: 0.05
